default_language_version:
  python: python3.7
default_stages: [commit, push]
fail_fast: true

repos:
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
    - id: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.761'
    hooks:
    -   id: mypy
        args: [--no-strict-optional, --ignore-missing-imports]